from gtts import gTTS
import os
from pathlib import Path

def text_to_wav(text, output_path="./data/input/generated_speech.wav"):
    """Convert text to WAV file using Google TTS"""
    # Create output directory if it doesn't exist
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    
    # Create gTTS object
    tts = gTTS(text=text, lang='en')
    
    # Save as MP3 first (gTTS only outputs MP3)
    mp3_path = output_path.replace('.wav', '.mp3')
    tts.save(mp3_path)
    
    # Convert MP3 to WAV using ffmpeg
    os.system(f'ffmpeg -i {mp3_path} -acodec pcm_s16le -ar 16000 -ac 1 {output_path}')
    
    # Remove temporary MP3 file
    os.remove(mp3_path)
    
    return output_path

if __name__ == "__main__":
    # Your text to convert
    text = "This is sound generated by text"
    
    # Convert to WAV
    wav_path = text_to_wav(text)
    
    print(f"WAV file generated at: {wav_path}")
    
    # You can now use this WAV file with demo.py
    print("\nNow you can run:")
    print(f"python demo.py --id Obama1 --driving_audio {wav_path} --device cpu") 